### ISSUE TITLE
Failed to download firmware

### ISSUE THREAD

**Issue by audreylim** [maxgerhardt/pio-espidf-simple-ota-example#4]
Hello, thanks for providing this example. I followed the steps in the README, including checking the config

`[*] Skip server certificate CN fieldcheck`

However, I got this error:

```
I (5887) simple_ota_example: Starting OTA example task
I (5897) simple_ota_example: Attempting to download update from https://{ip-address}:8070/hello-world.bin
E (5907) esp-tls: [sock=54] connect() error: Host is unreachable
E (5907) esp-tls: Failed to open new connection
E (5917) transport_base: Failed to open a new connection
E (5917) HTTP_CLIENT: Connection failed, sock < 0
E (5927) esp_https_ota: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT
E (5937) esp_https_ota: Failed to establish HTTP connection
E (5937) simple_ota_example: Firmware upgrade failed
```

The binary is accessible from my browser.

Any idea why or where to look to debug this issue? Let me know if you need more info!

**Comment by maxgerhardt** [comment]
>The binary is accessible from my browser.

Could the ESP32 correctly connect to your configured home network? Your computer and the ESP32 are then in the same network?

From the computer, can you ping the IP address of the ESP32 successfzkky?

**Comment by audreylim** [comment]
Yes, they're in the same network. I'm able to access the bin server from my iPhone. 

I'm unable to ping the ESP32 IP address from my PC. Hmm.

Tried connecting PC and ESP32 to my phone's hotspot, this time the error was request timeout, instead of `Host is unreachable`.

**Comment by maxgerhardt** [comment]
Then something is still wrong in the network architecture, IP address, port or there's a firewall / host isolation involved.

Can you get both ESP32 and your PC in your regular home WiFi without the iPhone involved?

**Comment by audreylim** [comment]
Yes, also connected ESP32 and PC to my home WiFi, and got the `Host is unreachable` error. I'm looking at this similar issue now, hoping its a lead https://github.com/espressif/esp-idf/issues/10112. Will let you know if I find a solution.

**Comment by audreylim** [comment]
Just wanted to quickly update a few more findings. Replaced the server IP with https://example.com and got this:

```
I (5887) simple_ota_example: Starting OTA example task
I (5897) simple_ota_example: Attempting to download update from https://example.com
E (5907) esp-tls: couldn't get hostname for :example.com: getaddrinfo() returns 202, addrinfo=0x0
E (5907) esp-tls: Failed to open new connection
E (5917) transport_base: Failed to open a new connection
E (5917) HTTP_CLIENT: Connection failed, sock < 0
E (5927) esp_https_ota: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT
E (5937) esp_https_ota: Failed to establish HTTP connection
E (5937) simple_ota_example: Firmware upgrade failed
```

Replaced the server IP with http://example.com and got this:
```
I (5887) simple_ota_example: Starting OTA example task
I (5897) simple_ota_example: Attempting to download update from http://example.com
I (6727) esp_netif_handlers: example_netif_sta ip: 192.168.0.16, mask: 255.255.255.0, gw: 192.168.0.1
I (6727) example_connect: Got IPv4 event: Interface "example_netif_sta" address: 192.168.0.16
I (7177) HTTP_CLIENT: Body received in fetch header state, 0x3ffb8e8c, 156
I (7177) esp_https_ota: Starting OTA...
I (7177) esp_https_ota: Writing to partition subtype 16 at offset 0x110000
E (7187) esp_https_ota: Mismatch chip id, expected 0, found 27757
E (7197) simple_ota_example: Firmware upgrade failed
```

Switching to my iPhone hotspot on the ESP, keeping the server IP https://example.com, I got:

```
I (5887) simple_ota_example: Starting OTA example task
I (5897) simple_ota_example: Attempting to download update from https://example.com
I (6327) esp-x509-crt-bundle: Certificate validated
I (7127) esp_https_ota: Starting OTA...
I (7137) esp_https_ota: Writing to partition subtype 16 at offset 0x110000
E (7137) esp_https_ota: Mismatch chip id, expected 0, found 27757
E (7147) simple_ota_example: Firmware upgrade failed
```

On the hotspot but switching back to the python bin server from this example:

```
I (7887) simple_ota_example: Starting OTA example task
I (7897) simple_ota_example: Attempting to download update from https://172.20.10.3:8070/hello-world.bin
E (7957) esp-x509-crt-bundle: Failed to verify certificate
E (7957) esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x3000
E (7967) esp-tls: Failed to open new connection
E (7967) transport_base: Failed to open a new connection
E (7977) HTTP_CLIENT: Connection failed, sock < 0
E (7977) esp_https_ota: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT
E (7987) esp_https_ota: Failed to establish HTTP connection
E (7987) simple_ota_example: Firmware upgrade failed
```

**Comment by maxgerhardt** [comment]
Weird, something is wrong with either DNS or routing tables.

My apologizes, I've not yet come to test it at home, but I'll do so tonight.

**Comment by audreylim** [comment]
Thank you! Yea I think it's related to the DNS/routing tables but I'm not sure how to fix it or where to look. FYI I also raised this [issue ](https://github.com/espressif/esp-idf/issues/10989) on esp-idf.

**Comment by maxgerhardt** [comment]
I can at least confirm you're not the only one having a problem, I also get
```
I (37912) wifi:connected with Vodafone-1E90, aid = 7, channel 11, BW20, bssid = 78:6a:1f:3b:b6:31
I (37912) wifi:security: WPA3-SAE, phy: bgn, rssi: -26
I (37912) wifi:pm start, type: 1

W (37922) wifi:<ba-add>idx:0 (ifx:0, 78:6a:1f:3b:b6:31), tid:0, ssn:0, winSize:64
W (37922) wifi:<ba-add>idx:1 (ifx:0, 78:6a:1f:3b:b6:31), tid:1, ssn:0, winSize:64
I (37992) wifi:AP's beacon interval = 102400 us, DTIM period = 1
W (38392) wifi:<ba-del>idx
W (38392) wifi:<ba-add>idx:1 (ifx:0, 78:6a:1f:3b:b6:31), tid:1, ssn:0, winSize:64
I (39882) example_connect: Got IPv6 event: Interface "example_netif_sta" address: fe80:0000:0000:0000:260a:c4ff:fe04:2638, type: ESP_IP6_ADDR_IS_LINK_LOCAL
I (39882) example_common: Connected to example_netif_sta
I (39892) example_common: - IPv6 address: fe80:0000:0000:0000:260a:c4ff:fe04:2638, type: ESP_IP6_ADDR_IS_LINK_LOCAL
I (39902) wifi:Set ps type: 0

I (39902) simple_ota_example: Starting OTA example task
I (39912) simple_ota_example: Attempting to download update from https://192.168.0.114:8070/hello-world.bin
E (39922) esp-tls: [sock=54] connect() error: Host is unreachable
E (39922) esp-tls: Failed to open new connection
E (39932) transport_base: Failed to open a new connection
E (39932) HTTP_CLIENT: Connection failed, sock < 0
E (39942) esp_https_ota: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT
E (39952) esp_https_ota: Failed to establish HTTP connection
E (39952) simple_ota_example: Firmware upgrade failed
I (41882) esp_netif_handlers: example_netif_sta ip: 192.168.0.190, mask: 255.255.255.0, gw: 192.168.0.1
I (41882) example_connect: Got IPv4 event: Interface "example_netif_sta" address: 192.168.0.190
```

**Comment by maxgerhardt** [comment]
Though it's suspicious that OTA tries to already start working before it got an IPv4 address. It goes off directly after getting a link-local IPv6 address.

**Comment by maxgerhardt** [comment]
Aha. sdkconfig changes disabled a critical option to wait for the IP through a semaphore. This is why it returns early.

![grafik](https://user-images.githubusercontent.com/26485477/225453818-6c6c8341-2de3-4b19-9fbe-4818c191d422.png)

I'll quickly put the new sdkconfig.defaults file in it.

**Comment by maxgerhardt** [comment]
Okay removing our version of `components/protocol_common_examples...` and using the ESP-IDF built in one and regenerating the sdkconfig definitely solved the connection / does not wait for IPv4 issue.

![grafik](https://user-images.githubusercontent.com/26485477/225454992-84802056-e2df-482f-b523-55f467b18225.png)

Now there's a -0x2700 = MBEDTLS_ERR_X509_CERT_VERIFY_FAILED error to debug.

**Comment by maxgerhardt** [comment]
Yes, I set CONFIG_MBEDTLS_CUSTOM_CERTIFICATE_BUNDLE=n to trigger the code that definitely loads the server.pem as supposed to try and it to the bundle and now

![grafik](https://user-images.githubusercontent.com/26485477/225457587-120faade-93d0-4a0a-9fe5-64345a008c11.png)

No idea why the other path doesn't work but I'll live with it.

**Comment by maxgerhardt** [comment]
It runs through for me now in an endless cycle. Also added a script that auto-copies the build firmware.bin to the http_server_root, so no manual copying.

Please completely remove your old copy of this repo, download it fresh and retry.

**Comment by audreylim** [comment]
@maxgerhardt thanks! It worked for me initially in an endless cycle too. After switching out the hello-world bin file with my bin file built with PlatformIO, the logs on PlatformIO show that the firmware was uploaded, but it wasn't:

On the python server:
```
192.168.0.16 - - [16/Mar/2023 09:55:34] "GET /hello-world.bin HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('192.168.0.16', 50034)
Traceback (most recent call last):
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 653, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 415, in handle_one_request
    method()
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 660, in do_GET
    self.copyfile(f, self.wfile)
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 860, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 198, in copyfileobj
    fdst_write(buf)
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 826, in write
    self._sock.sendall(b)
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1236, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\Audrey\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1205, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2384)
----------------------------------------
```

Running again a few more times (after switching our the hello-world.bin)

```
I (8234) simple_ota_example: Starting OTA example task
I (8244) simple_ota_example: Attempting to download update from https://192.168.0.15:8070/hello-world.bin
W (13364) esp-tls: Failed to open new connection in specified timeout
E (13364) transport_base: Failed to open a new connection
E (13364) HTTP_CLIENT: Connection failed, sock < 0
E (13364) esp_https_ota: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT
E (13374) esp_https_ota: Failed to establish HTTP connection
E (13384) simple_ota_example: Firmware upgrade failed
```

**Comment by audreylim** [comment]
Tried it again and it worked!

```

rst:0x1 (POWERON_RESET),boot:0x33 (SIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6940
ho 0 tail 12 room 4
load:0x40078000,len:15500
load:0x40080400,len:3844
entry 0x4008064c
I (28) boot: ESP-IDF 5.0.1 2nd stage bootloader
I (28) boot: compile time 10:33:48
I (28) boot: chip revision: v1.0
I (31) boot.esp32: SPI Speed      : 40MHz
I (36) boot.esp32: SPI Mode       : DIO
I (40) boot.esp32: SPI Flash Size : 4MB
I (45) boot: Enabling RNG early entropy source...
I (50) boot: Partition Table:
I (54) boot: ## Label            Usage          Type ST Offset   Length
I (61) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (69) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (76) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (84) boot:  3 factory          factory app      00 00 00010000 00100000
I (91) boot:  4 ota_0            OTA app          00 10 00110000 00100000
I (98) boot:  5 ota_1            OTA app          00 11 00210000 00100000
I (106) boot: End of partition table
I (110) boot: Defaulting to factory image
I (115) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=24e84h (151172) map
I (178) esp_image: segment 1: paddr=00034eac vaddr=3ffb0000 size=033c4h ( 13252) load
I (184) esp_image: segment 2: paddr=00038278 vaddr=40080000 size=07da0h ( 32160) load
I (197) esp_image: segment 3: paddr=00040020 vaddr=400d0020 size=95808h (612360) map
I (419) esp_image: segment 4: paddr=000d5830 vaddr=40087da0 size=0cef0h ( 52976) load
I (451) boot: Loaded app from partition at offset 0x10000
I (451) boot: Disabling RNG early entropy source...
I (463) cpu_start: Pro cpu up.
I (463) cpu_start: Starting app cpu, entry point is 0x400816b0
I (0) cpu_start: App cpu up.
I (479) cpu_start: Pro cpu start user code
I (479) cpu_start: cpu freq: 160000000 Hz
I (479) cpu_start: Application information:
I (484) cpu_start: Project name:     espidf_ota_example
I (490) cpu_start: App version:      2c18c3b-dirty
I (495) cpu_start: Compile time:     Mar 16 2023 10:33:34
I (501) cpu_start: ELF file SHA256:  c73ac4cb2c5dad3c...
I (507) cpu_start: ESP-IDF:          5.0.1
I (512) cpu_start: Min chip rev:     v0.0
I (517) cpu_start: Max chip rev:     v3.99 
I (522) cpu_start: Chip rev:         v1.0
I (527) heap_init: Initializing. RAM available for dynamic allocation:
I (534) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (540) heap_init: At 3FFB7610 len 000289F0 (162 KiB): DRAM
I (546) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (552) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (559) heap_init: At 40094C90 len 0000B370 (44 KiB): IRAM
I (566) spi_flash: detected chip: gd
I (569) spi_flash: flash io: dio
I (574) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (584) simple_ota_example: OTA example app_main start
I (614) simple_ota_example: SHA-256 for bootloader:  97c121ba48edaa2f13200b00f8c5320f7e320e585f6831fd5a8e43c9e4a1cedd
I (824) simple_ota_example: SHA-256 for current firmware:  ca791c2f5401ceebe82e2c497e7e5c7cf4bfccd16dd1a223c6a1c6bfd4a55e23
I (834) example_connect: Start example_connect.
I (844) wifi:wifi driver task: 3ffbf1e4, prio:23, stack:6656, core=0
I (844) system_api: Base MAC address is not set
I (844) system_api: read default base MAC address from EFUSE
I (854) wifi:wifi firmware version: 17afb16
I (854) wifi:wifi certification version: v7.0
I (864) wifi:config NVS flash: enabled
I (864) wifi:config nano formating: disabled
I (864) wifi:Init data frame dynamic rx buffer num: 32
I (874) wifi:Init management frame dynamic rx buffer num: 32
I (874) wifi:Init management short buffer num: 32
I (884) wifi:Init dynamic tx buffer num: 32
I (884) wifi:Init static rx buffer size: 1600
I (894) wifi:Init static rx buffer num: 10
I (894) wifi:Init dynamic rx buffer num: 32
I (894) wifi_init: rx ba win: 6
I (904) wifi_init: tcpip mbox: 32
I (904) wifi_init: udp mbox: 6
I (914) wifi_init: tcp mbox: 6
I (914) wifi_init: tcp tx win: 5744
I (914) wifi_init: tcp rx win: 5744
I (924) wifi_init: tcp mss: 1440
I (924) wifi_init: WiFi IRAM OP enabled
I (934) wifi_init: WiFi RX IRAM OP enabled
I (934) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (1044) wifi:mode : sta (94:b9:7e:e2:54:ac)
I (1044) wifi:enable tsf
I (1054) example_connect: Connecting to BCW710J-D137C-G...
I (1054) example_connect: Waiting for IP(s)
I (3464) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
I (4144) wifi:state: init -> auth (b0)
I (4144) wifi:state: auth -> assoc (0)
I (4154) wifi:state: assoc -> run (10)
I (4164) wifi:<ba-add>idx:0 (ifx:0, fc:4a:e9:31:85:52), tid:0, ssn:0, winSize:64
I (4184) wifi:connected with BCW710J-D137C-G, aid = 3, channel 1, BW20, bssid = fc:4a:e9:31:85:52
I (4184) wifi:security: WPA2-PSK, phy: bgn, rssi: -57
I (4194) wifi:pm start, type: 1

I (4284) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (5834) example_connect: Got IPv6 event: Interface "example_netif_sta" address: fe80:0000:0000:0000:96b9:7eff:fee2:54ac, type: ESP_IP6_ADDR_IS_LINK_LOCAL
I (8694) esp_netif_handlers: example_netif_sta ip: 192.168.0.16, mask: 255.255.255.0, gw: 192.168.0.1
I (8694) example_connect: Got IPv4 event: Interface "example_netif_sta" address: 192.168.0.16
I (8704) example_common: Connected to example_netif_sta
I (8704) example_common: - IPv4 address: 192.168.0.16,
I (8714) example_common: - IPv6 address: fe80:0000:0000:0000:96b9:7eff:fee2:54ac, type: ESP_IP6_ADDR_IS_LINK_LOCAL
I (8724) wifi:Set ps type: 0

I (8724) simple_ota_example: Starting OTA example task
I (8734) simple_ota_example: Attempting to download update from https://192.168.0.15:8070/firmware.bin
I (9354) esp_https_ota: Starting OTA...
I (9364) esp_https_ota: Writing to partition subtype 16 at offset 0x110000
I (34174) esp_image: segment 0: paddr=00110020 vaddr=3f400020 size=4213ch (270652) map
I (34254) esp_image: segment 1: paddr=00152164 vaddr=3ffbdb60 size=02448h (  9288) 
I (34264) esp_image: segment 2: paddr=001545b4 vaddr=40080000 size=0b918h ( 47384) 
I (34274) esp_image: segment 3: paddr=0015fed4 vaddr=00000000 size=0013ch (   316) 
I (34284) esp_image: segment 4: paddr=00160018 vaddr=400d0018 size=895a0h (562592) map
I (34454) esp_image: segment 0: paddr=00110020 vaddr=3f400020 size=4213ch (270652) map
I (34534) esp_image: segment 1: paddr=00152164 vaddr=3ffbdb60 size=02448h (  9288) 
I (34544) esp_image: segment 2: paddr=001545b4 vaddr=40080000 size=0b918h ( 47384) 
I (34554) esp_image: segment 3: paddr=0015fed4 vaddr=00000000 size=0013ch (   316) 
I (34564) esp_image: segment 4: paddr=00160018 vaddr=400d0018 size=895a0h (562592) map
I (34774) simple_ota_example: OTA Succeed, Rebooting...
I (34774) wifi:state: run -> init (0)
I (34774) wifi:pm stop, total sleep time: 2785041 us / 30580315 us

I (34774) wifi:<ba-del>idx
I (34774) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
I (34794) wifi:flush txq
I (34794) wifi:stop sw txq
I (34794) wifi:lmac stop hw txq
I (34794) wifi:Deinit lldesc rx mblock:10
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6940
ho 0 tail 12 room 4
load:0x40078000,len:15500
load:0x40080400,len:3844
entry 0x4008064c
I (29) boot: ESP-IDF 5.0.1 2nd stage bootloader
I (29) boot: compile time 10:33:48
I (29) boot: chip revision: v1.0
I (32) boot.esp32: SPI Speed      : 40MHz
I (37) boot.esp32: SPI Mode       : DIO
I (41) boot.esp32: SPI Flash Size : 4MB
I (46) boot: Enabling RNG early entropy source...
I (51) boot: Partition Table:
I (55) boot: ## Label            Usage          Type ST Offset   Length
I (62) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (69) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (77) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (84) boot:  3 factory          factory app      00 00 00010000 00100000
I (92) boot:  4 ota_0            OTA app          00 10 00110000 00100000
I (99) boot:  5 ota_1            OTA app          00 11 00210000 00100000
I (107) boot: End of partition table
I (111) esp_image: segment 0: paddr=00110020 vaddr=3f400020 size=4213ch (270652) map
I (217) esp_image: segment 1: paddr=00152164 vaddr=3ffbdb60 size=02448h (  9288) load
I (221) esp_image: segment 2: paddr=001545b4 vaddr=40080000 size=0b918h ( 47384) load
I (243) esp_image: segment 3: paddr=0015fed4 vaddr=00000000 size=0013ch (   316) 
I (243) esp_image: segment 4: paddr=00160018 vaddr=400d0018 size=895a0h (562592) map
I (457) boot: Loaded app from partition at offset 0x110000
I (457) boot: Disabling RNG early entropy source...
```

Thank you so much! I'll have to look into the differences between this copy and the esp-idf one to understand what's going on here. :)
